### ISSUE TITLE
Return nicer types for geofencing multi-polygons

### ISSUE THREAD

**Issue by leonardehrenfried** [entur/gbfs-java-model#58]
Right now the geofencing multipolygons are returned in quite an awkward type: `List<List<List<List<Double>>>>`

Since I'm planning to implement geofencing zones in OTP I was wondering if we could return a type like `org.geojson.MultiPolygon` from https://github.com/opendatalab-de/geojson-jackson.

The problem is that there appears to be not an easy way to override the generated java type unless you add it to the JSON schema. It's would only be a very small change to the schema but feels a bit dirty.

What do you think, @testower?

cc @hannesj

**Comment by testower** [comment]
Thanks @leonardehrenfried , I agree it's not idea. The problem of course is we can't modify the official json schema with changes that are specific for generating the java model. I really want to avoid maintaining a separate fork of the schema as well. We already have a few hacks in place (see README) just for that purpose.

For this particular problem, maybe the solution is to look into using the customRuleFactory option to create a way to intercept and handle MultiPolygons.

**Comment by hannesj** [comment]
A first step could be to use `{"$ref": "https://geojson.org/schema/MultiPolygon.json"}` for the geometry type in the [JSON schema](https://github.com/MobilityData/gbfs-json-schema/blob/master/v2.3/geofencing_zones.json#L104-L131). That could make easier to have the custom deserialization.

**Comment by leonardehrenfried** [comment]
Thanks for the suggestion, @hannesj. I will check it ou.

I've been exploring the customRuleFactory approach and here is what i have so far: https://github.com/ibi-group/gbfs-java-model/commit/018ac0d860090e6f4d46b452ae2d5de0dade2d58

The problem is that the Maven plugin classpath doesn't have access to the project's classpath so it cannot load the class.

Does anyone know how to get around that?

**Comment by testower** [comment]
Solved for now. I think still it's probably a good idea to follow @hannesj ' suggestion to refer to the official schema for geojson multipolygon in the gbfs schema. Do you want to make a PR for this there?
